version: '3.9'

volumes:
  mariadb_data: {}

services:
  mariadb:
    image: mariadb/server:10.4
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_PASSWORD=mypassword
      - MYSQL_USER=root
      - MYSQL_DATABASE=productsdb
# no hem funciona, he tingut que fer ->
# docker run -p 3306:3306 -d --name mariadb-fazt -e MYSQL_ROOT_PASSWORD=mypassword mariadb/server:10.4
# pensar com arreglar
